version: '3'

services:
  app:
    build: .
    image: moana-node
    command: amber watch
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
    - .:/app
    - nodes:/app/node_modules
    - shards:/app/lib

volumes:
  nodes:
  shards:
