version: '3'

services:
  app:
    build: .
    image: moana-node
    command: amber watch
    environment:
      PORT: ${PORT}
      NODE_ID: ${NODE_ID}
      CLUSTER_ID: ${CLUSTER_ID}
      MOANA_URL: ${MOANA_URL}
    ports:
      - ${PORT}:${PORT}
    volumes:
    - .:/app
    - nodes:/app/node_modules
    - shards:/app/lib

volumes:
  nodes:
  shards:
